ALTER TABLE "JobPost" ADD COLUMN "externalId" TEXT;
ALTER TABLE "JobPost" ADD COLUMN "salary" TEXT;
ALTER TABLE "JobPost" ADD COLUMN "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "JobPost" ADD COLUMN "url" TEXT;
ALTER TABLE "JobPost" ADD COLUMN "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX "JobPost_externalId_key" ON "JobPost"("externalId");
